package com.neuedu.vo;

import com.neuedu.pojo.Category;

import java.util.Date;
import java.util.Locale;

public class CategoryVO {
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_category.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_category.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_category.status
     *
     * @mbggenerated
     */
    private boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_category.sort_order
     *
     * @mbggenerated
     */
    private Integer sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_category.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_category.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_category.id
     *
     * @return the value of neuedu_category.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getParentId() {
        return parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean getStatus() {
        return status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    public Integer getSortOrder() {
        return sortOrder;
    }

    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public void assembleCategoryVO(Category category)
    {
        this.id=category.getId();
        this.parentId=category.getParentId();
        this.name=category.getName();
        if (category.getStatus()==null)
        {
            this.status=false;
        }
        else if (category.getStatus()==1)
        {
            this.status=true;
        }
        else {this.status=false;}
        this.sortOrder=category.getSortOrder();
        this.createTime=category.getCreateTime();
        this.updateTime=category.getUpdateTime();
    }
}
