package com.neuedu.dao;

import com.neuedu.pojo.Order;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Order record);


    Order findOrderByUserIdAndOrderNo(@Param(value = "userId") Integer userId ,@Param("orderNo") Long orderNo);

    Order findOrderByOrderNo(@Param("orderNo") Long orderNo);

    List<Order> findOrderByUserId(@Param(value = "userId") Integer userId);


    int send_goods(Order record);


    List<Order> searchOrderByOrderNo(@Param("orderNoMin") Long orderNoMin,@Param("orderNoMax") Long orderNoMax);

    List<Order> selectOrderByCreateTime(@Param("time")String closeTiom);

    int closeOrder(@Param("id")Integer id);
}