package com.neuedu.dao;

import com.neuedu.pojo.UserInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(@Param("userinfo") UserInfo record);




    int exsitsUsername(@Param("username") String username);


    UserInfo findByUsernameAndPassword(@Param("userinfo") UserInfo userInfo);

    int exsitsEmail(@Param("email") String email);

    String findQuestionByUsername(@Param("username") String username);


    UserInfo findQuestionAndQuestionByUsername(@Param("username") String username);


    int selectByUsernameAndPassword(@Param("username") String username,@Param("password") String password);



    int findByUsernameAndQuestionAndAnswer(@Param("username") String username,@Param("question") String question,@Param("answer") String answer);


    int resetPasswordByUsername(@Param("username") String username,@Param("password") String password);


}